apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: matveevali-ambulance-ufe
spec:
  module-uri:
    http://matveevali-ambulance-ufe.wac-hospital/build/ambulance-ufe.esm.js
    # module webkubectl kustomize ./apps/<pfx>-ambulance-ufe/s komponentu pre tento mikroFE
    # - umiestnený v namespace wac-hospital
  navigation:
    - element:
        matveevali-ambulance-wl-app # element, ktorý bude vložený na stránku pri navigácii na zoznam čakajúcich
      attributes:
        - name: api-base
          value: http://localhost:30081/api
        - name: ambulance-id
          value: bobulova
      path: matveevali-ambulance-wl # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Zoznam čakajúcich matveevali # názov mikro aplikácie
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
  preload: false # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy:
    true # pre komponenty v rámci klastra, neprístupné na verejnej sieti
    # musí byť táto hodnota nastavená na true
  hash-suffix:
    v1alpha2 # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
    # sa mení názov URL pre modul a tým je možné predísť problémom
    # s verziami vo vyrovnávacích pamätiach
